version: '3'

services:
  rest-book:
    build: ./
    command: ./wait-for-postgres.sh db ./restBook
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - '5432:5432'
